version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: markets_demo
      MYSQL_DATABASE: markets_database
      MYSQL_USER: markets_demo
      MYSQL_PASSWORD: markets_demo
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./markets_api:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql

volumes:
  mysql_data: