version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: markets_demo
      MYSQL_DATABASE: markets_database
      MYSQL_USER: markets_demo
      MYSQL_PASSWORD: markets_demo
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./markets_api:/var/www/html
      - ./markets_api/public:/var/www/html/public
      - ./markets_api/public/.htaccess:/var/www/html/public/.htaccess      
      - ./markets_api/laravel.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - mysql
    links:
      - mysql

volumes:
  mysql_data: